<?php

use Joaopaulolndev\FilamentGeneralSettings\Enums\TypeFieldEnum;
use Joaopaulolndev\FilamentGeneralSettings\Models\GeneralSetting;

return [
    'model' => GeneralSetting::class,
    'show_application_tab' => true,
    'show_logo_and_favicon' => false,
    'show_analytics_tab' => false,
    'show_seo_tab' => false,
    'show_email_tab' => false,
    'show_social_networks_tab' => false,
    'expiration_cache_config_time' => 60,
    'show_custom_tabs' => true,
    'custom_tabs' => [
        'more_configs' => [
            'label' => 'Attendance Flow',
            'icon' => 'heroicon-o-clock',
            'columns' => 1,
            'fields' => [
                'time_in_start' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Time In',
                    'placeholder' => '08:00',
                    'tooltip' => 'Start time used to decide late arrivals and default time-in behavior.',
                    'required' => true,
                    'rules' => ['required', 'date_format:H:i'],
                ],
                'time_out_start' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Time Out',
                    'placeholder' => '18:00',
                    'tooltip' => 'Scheduled end time used for time-out, undertime, overtime, and auto-closing old open records.',
                    'required' => true,
                    'rules' => ['required', 'date_format:H:i'],
                ],
                'max_breaks_per_day' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Breaks Per Day',
                    'placeholder' => '2',
                    'tooltip' => 'Maximum auto break-start taps allowed within one open attendance day.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:0', 'max:24'],
                ],
                'first_break_limit_minutes' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'First Break Limit Minutes',
                    'placeholder' => '60',
                    'tooltip' => 'Allowed minutes snapshot for the first completed break, typically lunch.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:1440'],
                ],
                'additional_break_limit_minutes' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Additional Break Limit Minutes',
                    'placeholder' => '15',
                    'tooltip' => 'Allowed minutes snapshot for each completed break after the first.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:1440'],
                ],
                'duplicate_scan_window_seconds' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Duplicate Scan Window Seconds',
                    'placeholder' => '60',
                    'tooltip' => 'Short retry window for scanner double-reads. Matching scans in this window reuse the existing attendance record.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:0', 'max:3600'],
                ],
                'same_employee_auth_cooldown_minutes' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Same Employee Auth Cooldown Minutes',
                    'placeholder' => '60',
                    'tooltip' => 'Minimum wait before the same employee can record another attendance event. Set 0 to disable.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:0', 'max:1440'],
                ],
                'face_capture_width_ratio' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face Capture Width Ratio',
                    'placeholder' => '0.50',
                    'tooltip' => 'Width of the centered camera crop sent for face enrollment and attendance. Use 0.25 to 1.00.',
                    'required' => true,
                    'rules' => ['required', 'numeric', 'min:0.25', 'max:1'],
                ],
                'face_capture_height_ratio' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face Capture Height Ratio',
                    'placeholder' => '0.68',
                    'tooltip' => 'Height of the centered camera crop sent for face enrollment and attendance. Use 0.25 to 1.00.',
                    'required' => true,
                    'rules' => ['required', 'numeric', 'min:0.25', 'max:1'],
                ],
                'face_verification_window_ms' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face Verification Window Milliseconds',
                    'placeholder' => '6000',
                    'tooltip' => 'Maximum time the kiosk spends collecting usable face frames before accepting or rejecting.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:4000', 'max:15000'],
                ],
                'face_usable_frame_target' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Scoped Face Usable Frame Target',
                    'placeholder' => '3',
                    'tooltip' => 'Frames to collect after RFID, keypad, or fingerprint already identified the employee.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:10'],
                ],
                'face_required_match_count' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Scoped Face Required Match Count',
                    'placeholder' => '2',
                    'tooltip' => 'How many scoped usable frames must match the already identified employee.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:10'],
                ],
                'face_only_usable_frame_target' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face-Only Usable Frame Target',
                    'placeholder' => '5',
                    'tooltip' => 'Frames to collect when face recognition starts without RFID, keypad, or fingerprint.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:10'],
                ],
                'face_only_required_match_count' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face-Only Required Match Count',
                    'placeholder' => '3',
                    'tooltip' => 'How many face-only frames must agree on the same recognized employee.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:10'],
                ],
                'face_attempt_retention_days' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Face Attempt Retention Days',
                    'placeholder' => '30',
                    'tooltip' => 'Days to keep face attempt logs and saved evidence media before automatic deletion.',
                    'required' => true,
                    'rules' => ['required', 'integer', 'min:1', 'max:3650'],
                ],
                'show_face_attendance_button' => [
                    'type' => TypeFieldEnum::Boolean->value,
                    'label' => 'Show Facial Recognition Attendance Button',
                    'tooltip' => 'Shows or hides the standalone face-only attendance button on the kiosk.',
                ],
                'show_scan_status_messages' => [
                    'type' => TypeFieldEnum::Boolean->value,
                    'label' => 'Show Home Scanner Status Messages',
                    'tooltip' => 'Shows or hides scanner status text on the home kiosk.',
                ],
                'scan_status_idle' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Scanner Idle Message',
                    'placeholder' => 'RFID and fingerprint scanners are listening.',
                    'tooltip' => 'Message shown while the kiosk is waiting for RFID or fingerprint input.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                'scan_status_rfid_not_recognized' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'RFID Not Recognized Message',
                    'placeholder' => 'RFID card not recognized.',
                    'tooltip' => 'Message shown when an RFID scan does not match any employee.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                'scan_status_fingerprint_waiting' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Fingerprint Waiting Message',
                    'placeholder' => 'Scan your registered finger on the scanner.',
                    'tooltip' => 'Message shown while the fingerprint scanner is waiting for a finger.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                'scan_status_fingerprint_not_found' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Fingerprint Not Found Message',
                    'placeholder' => 'Fingerprint not found.',
                    'tooltip' => 'Message shown when the scanner cannot match the fingerprint.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                'scan_status_fingerprint_matched' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Fingerprint Matched Message',
                    'placeholder' => 'Fingerprint matched. Starting facial verification...',
                    'tooltip' => 'Message shown after fingerprint match and before face verification starts.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
                'scan_status_attendance_recorded' => [
                    'type' => TypeFieldEnum::Text->value,
                    'label' => 'Attendance Recorded Message',
                    'placeholder' => 'Attendance recorded successfully.',
                    'tooltip' => 'Message shown after attendance is successfully saved.',
                    'required' => false,
                    'rules' => ['nullable', 'string', 'max:255'],
                ],
            ],
        ],
    ],
];
